function s = two_imgs(incrmnt)
%Takes a background+distractor image generated by obj_bg() and generates 
%sets of images with a moving target
% @param incrmnt is how many pixels the target moves between 'frames'
cd ('/Users/cass/Desktop/bg_3');
load metanew;
%Selects index of target images   
selObj = nan;
for i = 1:10
    obj = i*100-99:i*100;
    selObj = [selObj,randsample(obj,10,false)];
end
selObj(1)=[];
images = zeros(1024,1024,100, 'uint8');
bg = zeros(1024,1024,100, 'uint8');
%reads in target images and background+distractor images
for i = 0:99
    cd ('/Users/cass/Dropbox/jocasta_shared_folder/img_no_bg')
    images(:,:,i+1) = imread(['im', num2str((selObj(i+1)-1)),'.png']);
    	meta(i+1).seed_number = selObj(i+1)-1;
    cd ('/Users/cass/Desktop/bg_3')
    bg(:,:,i+1) = imread(['im', num2str(i),'.png']); 
end

cd ('/Users/cass/Desktop/two_imgs_3')
cntr = 0;
disp(cntr);
%generates set of 18 'moving' images w/target based on orientation in meta
for i = 0:99
    currentOrientation = meta(i+1).currentOrientation;
    for k = 1:18
       switch(currentOrientation)
     
           case 'north'
             filename = sprintf('im%d.png', cntr); 
             imwrite(move_obj(images(:,:,i+1), bg(:,:,i+1), [0, -incrmnt * k]), filename);
             cntr = cntr +1;
             
             
           case 'south'
             filename = sprintf('im%d.png', cntr); 
             imwrite(move_obj(images(:,:,i+1), bg(:,:,i+1), [0, incrmnt * k]), filename);
             cntr = cntr+1;
             
           case 'west'
             filename = sprintf('im%d.png', cntr); 
             imwrite(move_obj(images(:,:,i+1), bg(:,:,i+1), [-incrmnt * k, 0]), filename);
             cntr = cntr+1;
             
           case 'east'
             filename = sprintf('im%d.png', cntr); 
             imwrite(move_obj(images(:,:,i+1), bg(:,:,i+1), [incrmnt * k, 0]), filename);
             cntr = cntr+1;
             
           case 'northwest'
             filename = sprintf('im%d.png', cntr); 
             imwrite(move_obj(images(:,:,i+1), bg(:,:,i+1), [-incrmnt * k * sqrt(2), -incrmnt * k * sqrt(2)]), filename);
             cntr = cntr+1;
             
           case 'northeast'
             filename = sprintf('im%d.png', cntr); 
             imwrite(move_obj(images(:,:,i+1), bg(:,:,i+1), [incrmnt * k * sqrt(2), -incrmnt * k * sqrt(2)]), filename);
             cntr = cntr+1;
             
           case 'southwest'
             filename = sprintf('im%d.png', cntr); 
             imwrite(move_obj(images(:,:,i+1), bg(:,:,i+1), [-incrmnt * k * sqrt(2), incrmnt * k * sqrt(2)]), filename);
             cntr = cntr+1;
             
           case 'southeast'
             filename = sprintf('im%d.png', cntr); 
             imwrite(move_obj(images(:,:,i+1), bg(:,:,i+1), [incrmnt * k * sqrt(2), incrmnt * k * sqrt(2)]), filename);
             cntr = cntr+1;
             
       end
    end
end
save('-v7.3','meta.mat','meta');